[login.errors]
E1 = "Unknow error appiered while loging in, please try it later or try different account."
E2 = "Sorry, your password was incorrect. Please double-check your password."
E3 = "An unknown error appiered, please try it latter."

[login]
username_label = "Phone number, username, or email"
password_label = "Password"
show_button = "Show"
hide_button = "Hide"
login_button = "Log in"
or = "Or"
login_with_facebook = "Log in with Facebook"
forgot_password = "Forgot password?"
content_report_first = "You can also"
content_report_middle = "report content you believe is unlawful"
content_report_last = "in your country without logging in."
signup_message = "Don't have an account?"
signup_button = "Sign up"
get_the_app = "Get the app."
main_error_message = "You must be logged in to your Instagram account to view the content."

[two_factor]
confirm_button = "Confirm"
code_label = "Security Code"
content_report_first = "You can also"
content_report_middle = "report content you believe is unlawful"
content_report_last = "in your country without logging in."
trust_this_device = "Trust this device"
no_ask = "We won't ask for a code next time"
get_the_app = "Get the app."
main_error = "A security code is required."

[two_factor.descriptions]
verificationCodeDescription1 = "Enter the code we sent via SMS to your mobile number:"
verificationCodeDescription2 = "Enter one of the 8-digit codes provided when you set up two-factor authentication."
verificationCodeDescription3 = "Enter a 6-digit login code generated by an authentication app."
verificationCodeDescription4 = "Enter a 6-digit login code received via WhatsApp."
verificationCodeDescription = "Enter your verification code."

[two_factor.change_decriptions]
methodA1B3 = "If you're unable to receive a security code by text message, you can get one from your"
methodA1B2 = "If you're unable to receive a security code by text message, you can use one of your"
methodA2B3 = "If you're unable to use a security code from your backup codes, you can get one from your"
methodA2B1 = "If you're unable to use a security code from your backup codes, you can get one by"
methodA3B1 = "If you're unable to use a login code from an authentication app, you can get one by"
methodA3B2 = "If you're unable to receive a login code from an authentication app, use one of your"
methodA4 = "If you're unable to receive a code via WhatsApp, you can" # Unsupported yet!!
nomethod = "Select an alternative option for receiving your verification code."

[two_factor.method_names]
text_message = "text message"
backup_codes = "backup codes"
authentication_app = "authentication app"
or1 = "or"
or2 = "or use one of your"
or3 = "or use one from your"

[two_factor.errors]
E1 = "Error while loading 2FA configuration."
E2 = "An error appiered while sending data, please try it later."
E3 = "Please wait a few minutes before you try again."
E4 = "A security code is required."
E5 = "Unknown error appiered, please try it again"
E6 = "Please check the security code and try again."